version: '3.9'

services:
  db:
    image: postgres:13.2
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - overlay
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d/

networks:
  overlay:
